[package]
name = "hellstone"
version = "0.1.0"
edition = "2024"

members = [
    "infrastructure",
]



















































































































































































































































    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    































[dependencies]
domain = { path = "crates/domain" }
